Task 4
rusteRR/company-database pull request #2
Opened 2023-12-17 14:08 UTC by Almos11

Добавлены скрипты вставки данных в таблицы

2023-12-17 14:17 UTC, rusteRR commented on All_scripts/main.sql
> +INSERT INTO position (name) VALUES
Предлагаю всё же остановиться на ключевых словах в lower case

2023-12-17 14:25 UTC, rusteRR commented on All_scripts/main.sql
> +    ('MR.Conference.01.001', 'OFC001'),
Вообще я предполагалось, что вместе `Conference` и `MeetingRoom` будут коды офисов, где расположены переговорки

Но так как это небольшой фикс, можно сделать в следующем PR

2023-12-17 14:26 UTC, rusteRR commented on All_scripts/main.sql
> +    ('OFC001', 'Headquarters', 'New York'),
`office_code` потом тоже заменить на что-то более компактное из серии SPB-F

2023-12-17 14:28 UTC, rusteRR commented on All_scripts/main.sql
> +    ('OFC001', 'Headquarters', 'New York'),
`office_code` можно поправить, чтобы он был более осмысленным, например SPB-L, город и часть названия БЦ. 

Вообще, наверное, добавлю check на регулярку в `office_code`

2023-12-17 14:29 UTC, artsidorenko requested changes

2023-12-17 14:29 UTC, artsidorenko commented on All_scripts/main.sql
Зачем нам этот файл? Может просто ребейз на мастер сделать?

2023-12-17 14:29 UTC, artsidorenko commented on All_scripts/main.sql
> +INSERT INTO employee (position_id, first_name, second_name, birth_date, phone_number, salary, load, valid_from, valid_to) VALUES
Давай добавим уволившихся сотрудников

2023-12-17 14:29 UTC, artsidorenko commented on All_scripts/main.sql
> +INSERT INTO pass (employee_id, is_valid) VALUES
аналогично добавим невалидные пропуска

2023-12-17 14:29 UTC, artsidorenko commented on All_scripts/main.sql
> +    (1, 'OFC001', '2023-01-10 14:55', true),
Хочется видеть и выходы

2023-12-17 19:14 UTC, Almos11 commented on All_scripts/main.sql
> +    ('OFC001', 'Headquarters', 'New York'),
БЦ - бизнес центр?

2023-12-17 19:15 UTC, rusteRR commented on All_scripts/main.sql
> +    ('OFC001', 'Headquarters', 'New York'),
да

2023-12-20 17:33 UTC, artsidorenko approved these changes

2023-12-20 17:33 UTC, merged